# Site settings
name: Thomas Guégan
title: Thomas Guégan | Software Engineer and more
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Barbiche's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
tags:
- blog
- dev
- game development
menu:
- title: Home
  url: /
- title: About
  url: /about
- title: Contact
  url: /contact
show_hero: true # Show or not the most recent article in the front page.

# Social Media Settings
github_username: Barbiche
twitter_username: TheBarbiche
instagram_username: TheBarbiche
itch_username: barbiche
cv: true
formspree_form_id: mqkjqjne # id Formspree for contact page

# Posts Settings
show_time_bar: false # Article timebar, quite ugly to me.
two_columns_layout: true # Activate the second column for posts, showing the "See also" section.

# Build settings
logo: assets/img/logo.png
github: [metadata]
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-content

# SASS
sass:
  style: compressed

# Content paginator - Disabled for :num permalink bug to solve
# paginate_content:
# enabled: true
# debug: false
# collections:
#   - posts
# auto: false
# separator: "--page-break--"
# permalink: "/:num/"
# seo_canonical: true
# properties:
#   part:
#     is_generated: true
#   last:
#     is_generated: true
#   single:
#     is_generated: true